### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by Deftu** [Si1kn/mcp-client-snippits#1]
1. Repository name misspelled. "mcp-client-snippits" -> "mcp-client-snippets"
2. README misspelling. "compily" -> "comply"
3. Capitalization in sub-repository(?) names.
"auto-gg-mcp" -> "AutoGG-MCP"
"dabMod" -> "DabMod-MCP"
"fpsMod" -> "FPSMod-MCP"
"optifine" -> "Optifine-1.8.8-(insert optifine version naming conventions)"
"pingMod" -> "PingMod-MCP"
"purchaseApi" -> "PurchaseAPI"
"sparkApi" -> "SparkAPI-MC"
"youtubeSubMod" -> "YouTubeSubMod-MCP"

**Comment by Vidwangowdahm** [comment]
@MatthewTGM @Si1kn  I would like to correct the spelling mistakes in this code

**Comment by Deftu** [comment]
> @MatthewTGM @Si1kn I would like to correct the spelling mistakes in this code

He hasn't replied for nearly 4 days :/

**Comment by Si1kn** [comment]
Yes i will get onto this. Thanks 👍
